'use client';
import {useState} from 'react';
import {BlockEditor,SliderEditor} from './editor';
import {mediaUrl,type StoreBlock} from '../../../lib/storefront-content';
const labels={hero:'Hero banner',wide:'Banner lebar',split:'Gambar + teks',pair:'Dua gambar'};
export function VisualEditor({brand,name,blocks,auto,seconds}:{brand:string;name:string;blocks:StoreBlock[];auto:boolean;seconds:number}){
 const [selected,setSelected]=useState(blocks[0]?.id??'new'),[mobile,setMobile]=useState(false),[notice,setNotice]=useState('');
 const block=blocks.find(b=>b.id===selected);
 const ordered=[...blocks.filter(b=>b.kind==='hero'),...blocks.filter(b=>b.kind!=='hero')];
 function choose(id:string){setSelected(id);setNotice('');requestAnimationFrame(()=>document.getElementById(`preview-${id}`)?.scrollIntoView({behavior:'smooth',block:'nearest'}));}
 return <div className="appearance-workspace"><aside className="appearance-controls"><nav className="section-picker" aria-label="Bahagian kedai">{ordered.map((b,i)=><button key={b.id} type="button" className={selected===b.id?'':'secondary'} aria-pressed={selected===b.id} onClick={()=>choose(b.id)}>{i+1}. {b.heading||labels[b.kind]}{!b.active?' · Tersembunyi':''}</button>)}<button type="button" className={selected==='new'?'':'secondary'} onClick={()=>choose('new')}>+ Bahagian baharu</button><button type="button" className={selected==='slider'?'':'secondary'} onClick={()=>choose('slider')}>Tetapan slider</button></nav>{notice&&<p role="status" className="notice success">{notice}</p>}{selected==='slider'?<SliderEditor brand={brand} auto={auto} seconds={seconds}/>:<BlockEditor key={block?.id??'new'} brand={brand} block={block} position={Math.max(0,...blocks.map(b=>b.position))+10} onSaved={id=>{setSelected(id);setNotice('Disimpan — preview telah dikemas kini.');}}/>}</aside><section className="appearance-preview" aria-label="Preview kedai"><div className="preview-toolbar"><strong>Preview susun atur</strong><div><button className={!mobile?'':'secondary'} aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button className={mobile?'':'secondary'} aria-pressed={mobile} onClick={()=>setMobile(true)}>Telefon</button></div></div><p className="preview-help">Klik bahagian untuk edit. Preview menggunakan kandungan tersimpan; rupa kedai sebenar mungkin berbeza.</p><div className={`preview-canvas ${mobile?'phone':''}`}><header>{name}<small>KOLEKSI · TENTANG KAMI</small></header>{!blocks.some(b=>b.kind==='hero')&&<button className="preview-empty" onClick={()=>choose('new')}>+ Tambah hero banner di sini</button>}{ordered.filter(b=>b.kind==='hero').map(b=><PreviewBlock key={b.id} block={b} selected={selected===b.id} mobile={mobile} onSelect={()=>choose(b.id)}/>)}<div className="preview-products"><strong>Koleksi produk</strong><p>Produk kedai dipaparkan di bahagian ini.</p><div><span/><span/><span/></div></div>{ordered.filter(b=>b.kind!=='hero').map(b=><PreviewBlock key={b.id} block={b} selected={selected===b.id} mobile={mobile} onSelect={()=>choose(b.id)}/>)}<footer>{name} · Footer kedai</footer></div><small>Bahagian tersembunyi ditunjukkan dengan garis putus-putus untuk semakan owner.</small></section></div>;
}
function PreviewBlock({block:b,selected,mobile,onSelect}:{block:StoreBlock;selected:boolean;mobile:boolean;onSelect:()=>void}){
 const image=mediaUrl(mobile?(b.mobile_path||b.storage_path):b.storage_path);
 return <button id={`preview-${b.id}`} type="button" aria-pressed={selected} className={`preview-block ${b.kind} ${selected?'selected':''} ${!b.active?'hidden-section':''}`} onClick={onSelect}><span className="preview-block-label">{labels[b.kind]}{!b.active?' · Disembunyikan':''}</span><div className="preview-block-content">{image?<img src={image} alt={b.alt_text||''}/>:<div className="preview-image-placeholder">Gambar belum ditambah</div>}{b.kind==='pair'&&(b.second_path?<img src={mediaUrl(b.second_path)} alt="Gambar kedua"/>:<div className="preview-image-placeholder">Gambar kedua</div>)}<div className="preview-copy">{b.heading&&<strong>{b.heading}</strong>}{b.body&&<p>{b.body}</p>}{b.button_label&&<span>{b.button_label}</span>}</div></div></button>;
}
