'use server';
import {revalidatePath} from 'next/cache';
import sharp from 'sharp';
import {requireOwner} from '../../../../lib/auth';
import {parseProductDetails,parseVariant,requiredId,shortText} from '../../../../lib/hq-input';
import {selectedBrand} from '../../../../lib/hq';
export type SaveResult={error:string;success?:string};
const refresh=(id:string)=>{revalidatePath(`/admin/products/${id}`);revalidatePath('/admin');revalidatePath('/');revalidatePath('/preview/heritage');};
const failure=(e:unknown)=>({error:e instanceof Error?e.message:'Perubahan tidak dapat disimpan. Cuba lagi.'});
export async function saveDetails(_:SaveResult,form:FormData):Promise<SaveResult>{const {supabase}=await requireOwner();try{const id=requiredId(form.get('product_id')),input=parseProductDetails(form);if(input.status==='published'){const [{data:variants,error:ve},{data:images,error:ie}]=await Promise.all([supabase.from('product_variants').select('id').eq('product_id',id).eq('active',true).limit(1),supabase.from('product_images').select('id').eq('product_id',id).limit(1)]);if(ve||ie)throw new Error('Semakan produk gagal. Cuba lagi.');if(!variants?.length||!images?.length)throw new Error('Tambah sekurang-kurangnya satu gambar dan satu varian aktif sebelum paparkan produk.');}const {data,error}=await supabase.from('products').update(input).eq('id',id).select('id').single();if(error||!data)throw new Error(error?.code==='23505'?'Slug sudah digunakan dalam kedai ini.':'Produk belum disimpan.');refresh(id);return {error:'',success:'Maklumat produk disimpan.'};}catch(e){return failure(e);}}
export async function saveVariant(_:SaveResult,form:FormData):Promise<SaveResult>{const {supabase}=await requireOwner();try{const input=parseVariant(form);const {error}=await supabase.rpc('hq_save_variant',input);if(error)throw new Error(error.code==='23505'?'SKU atau kombinasi saiz/warna sudah digunakan.':error.code==='40001'?'Stok berubah sejak halaman dibuka. Muat semula sebelum simpan.':error.message.includes('below reserved')?'Stok fizikal tidak boleh kurang daripada stok yang ditempah.':error.message.includes('active variant')?'Kekalkan satu varian aktif atau simpan produk sebagai draf dahulu.':'Varian belum disimpan. Semak data dan sambungan.');refresh(input.p_product_id);return {error:'',success:'Varian dan stok disimpan.'};}catch(e){return failure(e);}}
export async function uploadProductImage(_:SaveResult,form:FormData):Promise<SaveResult>{const {supabase}=await requireOwner();try{const id=requiredId(form.get('product_id'));const {data:product,error:pe}=await supabase.from('products').select('brand_id,brands(slug)').eq('id',id).single();if(pe||!product)throw new Error('Produk tidak dijumpai.');const brand=[product.brands].flat()[0]?.slug;if(!selectedBrand(brand))throw new Error('Brand belum disokong.');const position=Number(form.get('position'));if(!Number.isInteger(position)||position<0||position>9999)throw new Error('Susunan tidak sah.');const altText=shortText(form,'alt_text',300,false);const file=form.get('image');if(!(file instanceof File)||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size===0||file.size>3*1024*1024)throw new Error('Pilih JPG, PNG atau WebP, maksimum 3 MB.');const buffer=Buffer.from(await file.arrayBuffer());const metadata=await sharp(buffer,{limitInputPixels:40000000}).metadata();if(!['jpeg','png','webp'].includes(metadata.format??'')||(metadata.pages??1)>1)throw new Error('Gunakan gambar statik.');const output=await sharp(buffer,{limitInputPixels:40000000}).rotate().resize({width:2400,height:3000,fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();if(output.length>3*1024*1024)throw new Error('Gambar terlalu besar.');const path=`${brand}/${crypto.randomUUID()}.webp`;const {error:uploadError}=await supabase.storage.from('storefront-media').upload(path,output,{contentType:'image/webp',upsert:false});if(uploadError)throw new Error('Upload gagal. Cuba lagi.');const {error}=await supabase.from('product_images').insert({product_id:id,storage_path:path,alt_text:altText,position});if(error)throw new Error('Gambar dimuat naik tetapi belum dipautkan. Cuba lagi.');refresh(id);return {error:'',success:'Gambar ditambah.'};}catch(e){return failure(e);}}
export async function removeProductImage(_:SaveResult,form:FormData):Promise<SaveResult>{const {supabase}=await requireOwner();try{const id=requiredId(form.get('product_id')),image=requiredId(form.get('image_id'));const {data:product}=await supabase.from('products').select('status').eq('id',id).single();const {count,error:ce}=await supabase.from('product_images').select('id',{count:'exact',head:true}).eq('product_id',id);if(ce)throw new Error('Semakan gambar gagal.');if(product?.status==='published'&&(count??0)<=1)throw new Error('Tambah gambar pengganti atau simpan produk sebagai draf dahulu.');const {error}=await supabase.from('product_images').delete().eq('id',image).eq('product_id',id);if(error)throw new Error('Gambar belum dibuang.');refresh(id);return {error:'',success:'Gambar dikeluarkan daripada produk.'};}catch(e){return failure(e);}}

export async function quickSaveVariant(input:{id:string;productId:string;field:'price'|'stock';value:string;expected:string}) {
 const {supabase}=await requireOwner();
 try {
  const id=requiredId(input.id),productId=requiredId(input.productId);
  if(!['price','stock'].includes(input.field))throw new Error('Medan tidak sah.');
  const {data:v,error}=await supabase.from('product_variants').select('*,inventory(*)').eq('id',id).eq('product_id',productId).single();
  if(error||!v)throw new Error('Varian tidak dijumpai.');
  const form=new FormData();
  for(const [key,value] of Object.entries({product_id:productId,variant_id:id,sku:v.sku,size:v.size,color:v.color,price:input.field==='price'?input.value:String(v.price_cents/100),stock:input.field==='stock'?input.value:String(v.inventory?.on_hand??0),active:v.active?'on':'',updated_at:input.expected,reason:'Edit pantas HQ'}))form.set(key,String(value));
  const parsed=parseVariant(form);
  const {error:saveError}=await supabase.rpc('hq_save_variant',parsed);
  if(saveError)throw new Error(saveError.code==='40001'?'Data telah berubah. Muat semula sebelum cuba lagi.':saveError.message.includes('below reserved')?'Stok tidak boleh kurang daripada jumlah ditempah.':'Belum disimpan. Cuba lagi.');
  const {data:latest,error:readError}=await supabase.from('product_variants').select('*,inventory(*)').eq('id',id).single();
  refresh(productId);
  if(readError||!latest)throw new Error('Simpanan dihantar. Muat semula untuk sahkan nilai terkini.');
  return {error:'',variant:latest};
 }catch(e){return {...failure(e),variant:null};}
}
