'use client';
import {useActionState} from 'react';
import {Submit} from '../../submit';
import {saveDetails,saveVariant,uploadProductImage,removeProductImage,type SaveResult} from './actions';
const initial:SaveResult={error:''};
export type Variant={id:string;sku:string;size:string;color:string;price_cents:number;active:boolean;inventory:{on_hand:number;reserved:number;updated_at:string}|null};
function Feedback({state}:{state:SaveResult}){return state.error?<p className="notice error" role="alert">{state.error}</p>:state.success?<p className="notice success" role="status">{state.success}</p>:null}
export function DetailsForm({product}:{product:{id:string;name:string;slug:string;description:string;category:string;status:string}}){const [state,action]=useActionState(saveDetails,initial);return <form action={action}><input type="hidden" name="product_id" value={product.id}/><Feedback state={state}/><label>Nama produk<input name="name" required maxLength={160} defaultValue={product.name}/></label><div className="grid"><label>Kategori<select name="category" defaultValue={product.category}><option value="clothing">Baju</option><option value="headwear">Topi</option><option value="accessories">Aksesori</option></select></label><label>Status katalog<select name="status" defaultValue={product.status}><option value="draft">Draf — belum dipaparkan</option><option value="published">Dipaparkan dalam katalog</option><option value="archived">Arkib — disembunyikan</option></select></label></div><label>Penerangan<textarea name="description" maxLength={10000} defaultValue={product.description}/></label><details><summary>Pautan produk</summary><label>Slug<input name="slug" required maxLength={100} pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={product.slug}/><small>Perubahan slug boleh mengubah pautan produk.</small></label></details><div className="save-bar"><Submit>Simpan maklumat</Submit><small>Harga dan stok disimpan pada varian di bawah.</small></div></form>}
export function VariantForm({productId,variant}:{productId:string;variant?:Variant}){const [state,action]=useActionState(saveVariant,initial);return <form action={action} className="variant-form"><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="variant_id" value={variant?.id??''}/><input type="hidden" name="updated_at" value={variant?.inventory?.updated_at??''}/><Feedback state={state}/><div className="grid"><label>SKU<input name="sku" required maxLength={80} defaultValue={variant?.sku} placeholder="ASAS-TEE-BLK-M"/></label><label>Saiz<input name="size" required maxLength={60} defaultValue={variant?.size} placeholder="M / One size"/></label><label>Warna<input name="color" required maxLength={60} defaultValue={variant?.color} placeholder="Hitam"/></label><label>Harga (RM)<input name="price" type="number" required min="0" max="9999999.99" step="0.01" defaultValue={variant?(variant.price_cents/100).toFixed(2):''}/></label><label>Stok fizikal<input name="stock" type="number" min={variant?.inventory?.reserved??0} max="1000000" step="1" required defaultValue={variant?.inventory?.on_hand??0}/><small>Ditempah: {variant?.inventory?.reserved??0} · Boleh dijual: {(variant?.inventory?.on_hand??0)-(variant?.inventory?.reserved??0)}</small></label><label>Catatan stok<input name="reason" required maxLength={300} defaultValue={variant?'Semakan stok HQ':'Stok awal'} placeholder="Contoh: Restock 20 unit"/></label></div><div className="row"><label className="check"><input type="checkbox" name="active" defaultChecked={variant?.active??true}/>Varian aktif</label><Submit>{variant?'Simpan varian':'Tambah varian'}</Submit></div></form>}
export function ImageUpload({productId,position}:{productId:string;position:number}){const [state,action]=useActionState(uploadProductImage,initial);return <form action={action}><input type="hidden" name="product_id" value={productId}/><Feedback state={state}/><label>Gambar produk<input type="file" name="image" accept="image/jpeg,image/png,image/webp" required/><small>JPG, PNG atau WebP · maksimum 3 MB · gunakan gambar produk sebenar.</small></label><div className="grid"><label>Penerangan gambar<input name="alt_text" maxLength={300} placeholder="Baju plain hitam, pandangan depan"/></label><label>Susunan<input type="number" name="position" min="0" max="9999" required defaultValue={position}/><small>Nombor terkecil menjadi gambar utama.</small></label></div><Submit>Muat naik gambar</Submit></form>}
export function RemoveImage({productId,imageId}:{productId:string;imageId:string}){const [state,action]=useActionState(removeProductImage,initial);return <form action={action}><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="image_id" value={imageId}/><Feedback state={state}/><Submit>Buang dari produk</Submit></form>}
