import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireOwner} from '../../../../lib/auth';
import {rm,paymentLabels,fulfillmentLabels} from '../../../../lib/hq';
import {PrintOrder} from './print';
import {PackingForm} from './packing';
export default async function OrderDetail({params}:{params:Promise<{id:string}>}){
 const {supabase}=await requireOwner();const {id}=await params;
 if(!/^[0-9a-f-]{36}$/i.test(id))notFound();
 const {data:o,error}=await supabase.from('orders').select('*,order_items(*),fulfillments(*)').eq('id',id).maybeSingle();
 if(error)throw new Error('Order tidak dapat dimuatkan.');if(!o)notFound();
 const fulfillment=[o.fulfillments].flat()[0];const a=o.shipping_address as Record<string,unknown>;
 const labels:Record<string,string>={line1:'Alamat',line2:'Alamat tambahan',address:'Alamat',address_line1:'Alamat',address_line2:'Alamat tambahan',street_address:'Alamat',city:'Bandar',state:'Negeri',postcode:'Poskod',postal_code:'Poskod',zip_code:'Poskod',country:'Negara'};
 return <><Link className="breadcrumbs" href="/admin">← Semua order</Link><div className="row"><h1>Order #{o.order_number}</h1><PrintOrder/></div><div className="row"><span className="badge">{paymentLabels[o.payment_status]??o.payment_status}</span><span>{o.order_status==='cancelled'?'Dibatalkan':o.order_status==='completed'?'Selesai':'Aktif'}</span></div><div className="grid"><section className="card"><h2>Pelanggan</h2><p>{o.customer_name}<br/>{o.customer_email}<br/>{o.customer_phone}</p><h3>Alamat penghantaran</h3><dl>{Object.entries(a).map(([key,value])=><div key={key}><dt><small>{labels[key]??key}</small></dt><dd>{typeof value==='string'||typeof value==='number'?String(value):JSON.stringify(value)}</dd></div>)}</dl></section><section className="card"><h2>Packing & penghantaran</h2><p>{fulfillmentLabels[fulfillment?.status]??'Rekod penghantaran belum tersedia'}</p>{fulfillment?.tracking_number&&<p>{fulfillment.carrier} · {fulfillment.tracking_number}</p>}{fulfillment&&o.payment_status==='paid'&&o.order_status!=='cancelled'&&fulfillment.status!=='delivered'?<PackingForm orderId={o.id} status={fulfillment.status}/>:<p><small>{o.payment_status!=='paid'?'Packing hanya tersedia selepas bayaran disahkan.':'Tiada tindakan packing tersedia.'}</small></p>}</section></div><section className="card"><h2>Item order</h2><div className="scroll order-lines"><table><thead><tr><th>Produk / brand</th><th>Varian</th><th>Kuantiti</th><th>Jumlah</th></tr></thead><tbody>{o.order_items.map((i:{id:string;product_name:string;brand_name:string;sku:string;size:string;color:string;quantity:number;line_total_cents:number})=><tr key={i.id}><td>{i.product_name}<small>{i.brand_name}</small></td><td>{i.sku}<small>{i.size} · {i.color}</small></td><td>{i.quantity}</td><td>{rm(i.line_total_cents)}</td></tr>)}</tbody></table></div><p>Subtotal: {rm(o.subtotal_cents)} · Penghantaran: {rm(o.shipping_cents)} · Diskaun: {rm(o.discount_cents)}</p><strong>Jumlah: {rm(o.total_cents)}</strong></section></>;
}
